package com.example.aaron.greendao.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.example.aaron.greendao.db.PhoneStatus;

import com.example.aaron.greendao.db.PhoneStatusDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig phoneStatusDaoConfig;

    private final PhoneStatusDao phoneStatusDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        phoneStatusDaoConfig = daoConfigMap.get(PhoneStatusDao.class).clone();
        phoneStatusDaoConfig.initIdentityScope(type);

        phoneStatusDao = new PhoneStatusDao(phoneStatusDaoConfig, this);

        registerDao(PhoneStatus.class, phoneStatusDao);
    }
    
    public void clear() {
        phoneStatusDaoConfig.getIdentityScope().clear();
    }

    public PhoneStatusDao getPhoneStatusDao() {
        return phoneStatusDao;
    }

}
