package com.example.aaron.greendao.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PHONE_STATUS".
 */
public class PhoneStatus {

    private Long id;
    private Boolean isPowerOn;
    private java.util.Date date;
    private Double latitud;
    private Double longitud;
    private String locationProvider;
    private String address;
    private Boolean usbCharge;
    private Boolean acCharge;
    private Integer batteryLevel;
    private Integer bateryLevelScale;
    private Float batteryPtc;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PhoneStatus() {
    }

    public PhoneStatus(Long id) {
        this.id = id;
    }

    public PhoneStatus(Long id, Boolean isPowerOn, java.util.Date date, Double latitud, Double longitud, String locationProvider, String address, Boolean usbCharge, Boolean acCharge, Integer batteryLevel, Integer bateryLevelScale, Float batteryPtc) {
        this.id = id;
        this.isPowerOn = isPowerOn;
        this.date = date;
        this.latitud = latitud;
        this.longitud = longitud;
        this.locationProvider = locationProvider;
        this.address = address;
        this.usbCharge = usbCharge;
        this.acCharge = acCharge;
        this.batteryLevel = batteryLevel;
        this.bateryLevelScale = bateryLevelScale;
        this.batteryPtc = batteryPtc;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getIsPowerOn() {
        return isPowerOn;
    }

    public void setIsPowerOn(Boolean isPowerOn) {
        this.isPowerOn = isPowerOn;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public Double getLatitud() {
        return latitud;
    }

    public void setLatitud(Double latitud) {
        this.latitud = latitud;
    }

    public Double getLongitud() {
        return longitud;
    }

    public void setLongitud(Double longitud) {
        this.longitud = longitud;
    }

    public String getLocationProvider() {
        return locationProvider;
    }

    public void setLocationProvider(String locationProvider) {
        this.locationProvider = locationProvider;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Boolean getUsbCharge() {
        return usbCharge;
    }

    public void setUsbCharge(Boolean usbCharge) {
        this.usbCharge = usbCharge;
    }

    public Boolean getAcCharge() {
        return acCharge;
    }

    public void setAcCharge(Boolean acCharge) {
        this.acCharge = acCharge;
    }

    public Integer getBatteryLevel() {
        return batteryLevel;
    }

    public void setBatteryLevel(Integer batteryLevel) {
        this.batteryLevel = batteryLevel;
    }

    public Integer getBateryLevelScale() {
        return bateryLevelScale;
    }

    public void setBateryLevelScale(Integer bateryLevelScale) {
        this.bateryLevelScale = bateryLevelScale;
    }

    public Float getBatteryPtc() {
        return batteryPtc;
    }

    public void setBatteryPtc(Float batteryPtc) {
        this.batteryPtc = batteryPtc;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END


    @Override
    public String toString() {
        return "PhoneStatus{" +
                "id=" + id +
                ", isPowerOn=" + isPowerOn +
                ", date=" + date +
                ", latitud=" + latitud +
                ", longitud=" + longitud +
                ", locationProvider='" + locationProvider + '\'' +
                ", address='" + address + '\'' +
                ", usbCharge=" + usbCharge +
                ", acCharge=" + acCharge +
                ", batteryLevel=" + batteryLevel +
                ", bateryLevelScale=" + bateryLevelScale +
                ", batteryPtc=" + batteryPtc +
                '}';
    }
}
